

def take_attendance_v2(message):
    keyboard = [telebot.types.InlineKeyboardButton('Jan Cohort', callback_data='jan23'),
                telebot.types.InlineKeyboardButton('Feb Cohort', callback_data='feb23')]
    reply_markup = telebot.types.InlineKeyboardMarkup(keyboard)
    
    bot.send_message(message.chat.id, 'Select cohort', reply_markup=reply_markup)
    #bot.answer_callback_query

{'id': '5525289337528007518', 'from_user': {'id': 5581423968, 'is_bot': False, 'first_name': 'Sien Long', 'username': 'natuyuki', 'last_name': None, 'language_code': 'en', 'can_join_groups': None, 'can_read_all_group_messages': None, 'supports_inline_queries': None, 'is_premium': None, 'added_to_attachment_menu': None}, 'message': {'content_type': 'text', 'id': 46, 'message_id': 46, 'from_user': <telebot.types.User object at 0x0000017CB1B57D30>, 'date': 1681776599, 'chat': <telebot.types.Chat object at 0x0000017CB1B57E80>, 'sender_chat': None, 'forward_from': None, 'forward_from_chat': None, 'forward_from_message_id': None, 'forward_signature': None, 'forward_sender_name': None, 'forward_date': None, 'is_automatic_forward': None, 'reply_to_message': None, 'via_bot': None, 'edit_date': None, 'has_protected_content': None, 'media_group_id': None, 'author_signature': None, 'text': 'Select cohort', 'entities': None, 'caption_entities': None, 'audio': None, 'document': None, 'photo': None, 'sticker': None, 'video': None, 'video_note': None, 'voice': None, 'caption': None, 'contact': None, 'location': None, 'venue': None, 'animation': None, 'dice': None, 'new_chat_member': None, 'new_chat_members': None, 'left_chat_member': None, 'new_chat_title': None, 'new_chat_photo': None, 'delete_chat_photo': None, 'group_chat_created': None, 'supergroup_chat_created': None, 'channel_chat_created': None, 'migrate_to_chat_id': None, 'migrate_from_chat_id': None, 'pinned_message': None, 'invoice': None, 'successful_payment': None, 'connected_website': None, 'reply_markup': <telebot.types.InlineKeyboardMarkup object at 0x0000017CB1B57EE0>, 'message_thread_id': None, 'is_topic_message': None, 'forum_topic_created': None, 'forum_topic_closed': None, 'forum_topic_reopened': None, 'has_media_spoiler': None, 'forum_topic_edited': None, 'general_forum_topic_hidden': None, 'general_forum_topic_unhidden': None, 'write_access_allowed': None, 'user_shared': None, 'chat_shared': None, 'json': {'message_id': 46, 'from': {'id': 6108759039, 'is_bot': True, 'first_name': 'DigiPen Attendance Bot', 'username': 'digipen_attendance_bot'}, 'chat': {'id': 5581423968, 'first_name': 'Sien Long', 'username': 'natuyuki', 'type': 'private'}, 'date': 1681776599, 'text': 'Select cohort', 'reply_markup': {'inline_keyboard': [[{'text': 'Jan Cohort', 'callback_data': 'jan23'}, {'text': 'Feb Cohort', 'callback_data': 'feb23'}]]}}}, 'inline_message_id': None, 'chat_instance': '2588417505927912064', 'data': 'jan23', 'game_short_name': None, 'json': {'id': '5525289337528007518', 'from': {'id': 5581423968, 'is_bot': False, 'first_name': 'Sien Long', 'username': 'natuyuki', 'language_code': 'en'}, 'message': {'message_id': 46, 'from': {'id': 6108759039, 'is_bot': True, 'first_name': 'DigiPen Attendance 
Bot', 'username': 'digipen_attendance_bot'}, 'chat': {'id': 5581423968, 'first_name': 'Sien Long', 'username': 'natuyuki', 'type': 'private'}, 'date': 1681776599, 'text': 'Select cohort', 'reply_markup': {'inline_keyboard': [[{'text': 'Jan Cohort', 'callback_data': 'jan23'}, {'text': 'Feb Cohort', 'callback_data': 'feb23'}]]}}, 'chat_instance': '2588417505927912064', 'data': 'jan23'}}